eth-easl/modyn

.github/actions/conda/action.yml
.github/workflows/workflow.yaml
environment.yml
modyn/selector/internal/selector_strategies/abstract_selection_strategy.py

We did not release the SharedMemory objects we created. Now, we do using the SharedMemoryManager

Fix memory leak in selector using SharedMemoryManager

---

.github/actions/base/action.yml
docker-compose.yml
environment.yml
initial_setup.sh

Not sure how this happened, this basically reverted changes I made in #264.

Revert changes on environment and docker-compose made by #254

---

initial_setup.sh

Currently, we just read in the entire Dockerfile and append a new FROM statement to the beginning. These statements are being ignored, hence this did not have any effect.

Use image as set in `initial_setup.sh`

---

modyn/models/__init__.py
modyn/models/resnet50/__init__.py
modyn/models/resnet50/resnet50.py
modyn/tests/models/test_resnet50.py

This PR adds ResNet50 to Modyn.

Add ResNet50 Model

---

modyn/tests/trainer_server/internal/data/test_online_dataset.py
modyn/trainer_server/internal/dataset/online_dataset.py

- Lock around the log
- Change to `memoryview` to avoid unnecessary copies
- Actually delete already used data

Improvements to OnlineDataset

---

modyn/trainer_server/internal/dataset/extra_local_eval/README.md
modyn/trainer_server/internal/dataset/extra_local_eval/binary_file_wrapper.py
modyn/trainer_server/internal/dataset/extra_local_eval/cloc_local_dataset.py
modyn/trainer_server/internal/dataset/extra_local_eval/criteo_local_dataset.py

This adds some files required to load data locally.

Add local datasets required for experiments for arXiv submission

---

benchmark/criteo_1TB/execute_pipelines.sh
docker/Model_Storage/Dockerfile
docker/Selector/Dockerfile
modyn/model_storage/internal/grpc/model_storage_grpc_servicer.py
modyn/model_storage/internal/model_storage_manager.py

- Memory issues in model storage
- Docker file permissions

More leftovers from arXiv submission

---

.github/workflows/workflow.yaml

Run CI when pushing to main

---

modyn/config/schema/pipeline.py
modyn/supervisor/internal/evaluation_result_writer/__init__.py
modyn/supervisor/internal/evaluation_result_writer/abstract_evaluation_result_writer.py
modyn/supervisor/internal/evaluation_result_writer/json_result_writer.py
modyn/supervisor/internal/grpc/enums.py
modyn/supervisor/internal/grpc_handler.py
modyn/supervisor/internal/pipeline_executor/models.py
modyn/supervisor/internal/pipeline_executor/pipeline_executor.py
modyn/supervisor/internal/supervisor.py
modyn/tests/supervisor/internal/evaluation_result_writer/test_json_result_writer.py
modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py
modyn/tests/supervisor/internal/test_grpc_handler.py
modyn/tests/supervisor/internal/test_supervisor.py
modyn/tests/utils/test_utils.py
modyn/utils/utils.py

integrated suggestions of #437 and other adjustments that are needed to use the new setup for logging and plotting.
No need for dedicated review, I'll just merge this PR into the other one

feat: Adjust logging with more meta information for plotting

---

benchmark/mnist/mnist.yaml
benchmark/wildtime_benchmarks/benchmark_utils.py
benchmark/wildtime_benchmarks/data_generation_yearbook.py
benchmark/wildtime_benchmarks/example_pipelines/arxiv.yaml
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/arxiv_datadrift.yaml
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/huffpost_datadrift.yaml
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/yearbook_datadrift.yaml
benchmark/wildtime_benchmarks/example_pipelines/fmow.yaml
benchmark/wildtime_benchmarks/example_pipelines/huffpost.yaml
benchmark/wildtime_benchmarks/example_pipelines/yearbook.yaml
modyn/config/__init__.py
modyn/config/schema/pipeline.py
modyn/tests/config/test_config_integrity.py
modyn/tests/conftest.py
modyn/trainer_server/internal/dataset/key_sources/local_key_source.py
modynclient/config/examples/mnist.yaml

Let's ensure that our configs never get outdated. It should be the responsibility of the person who changes any configuration option, to update all actively used configs in the repo.

test: Add unit tests enforcing all configs to be up to date

---

modyn/config/__init__.py
modyn/config/schema/pipeline.py
modyn/selector/internal/selector_strategies/coreset_strategy.py
modyn/selector/internal/selector_strategies/downsampling_strategies/downsampling_scheduler.py
modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_scheduler.py
modyn/tests/selector/internal/selector_strategies/test_coreset_strategy.py

The logic to update downsampler is off (see the comments I added in `coreset_strategy.py`). This PR fixes it.

Fix downsampler update in downsampler scheduler

---

.github/workflows/workflow.yaml
README.md

Let's integrate codecov to get rid of the bulky coverage messages

feat: Add `codecov`

---

modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_uncertainty_downsampling_strategy.py
modyn/trainer_server/internal/trainer/remote_downsamplers/remote_uncertainty_downsampling_strategy.py

We had our own version of https://github.com/PatrickZH/DeepCore/issues/11 because our version of their implementation confused where the inversion is placed. I thought it through and think we don't need to do any inversion. I added some comments explaining the thoughts.
Note that this does not address https://github.com/PatrickZH/DeepCore/issues/13!

fix: Uncertainty based downsampler choosing the most certain samples

---

codecov.yml
modyn/config/examples/modyn_config.yaml
modyn/config/schema/pipeline/evaluation/config.py
modyn/config/schema/system/config.py
modyn/supervisor/internal/pipeline_executor/evaluation_executor.py

Per the title, this solves https://github.com/eth-easl/modyn/issues/508.

Move `after_pipeline|training_evaluation_workers` to pipeline config

---

modyn/evaluator/internal/grpc/evaluator_grpc_server.py
modyn/evaluator/internal/pytorch_evaluator.py
modyn/supervisor/internal/supervisor.py
modyn/trainer_server/internal/dataset/data_utils.py
modyn/trainer_server/internal/dataset/key_sources/local_key_source.py

This concludes the important changes I have on the SIGMOD branch. These changes are too small to open more PRs for them, so I grouped them in a single PR.

Small stability and logging fixes

---

benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/huffpost_datadrift.yaml
modyn/config/schema/pipeline/trigger/drift/alibi_detect.py
modyn/supervisor/internal/triggers/drift/alibi_detector.py
modyn/tests/supervisor/internal/triggers/test_datadrifttrigger.py

Support threshold-based triggering for alibi-detect MMD

---

benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/arxiv_datadrift.yaml
experiments/arxiv/compare_trigger_policies/run.py
experiments/huffpost/compare_trigger_policies/run.py
experiments/yearbook/compare_trigger_policies/run.py
modyn/config/schema/pipeline/trigger/drift/config.py
modyn/supervisor/internal/triggers/datadrifttrigger.py
modyn/supervisor/internal/triggers/trigger.py
modyn/supervisor/internal/triggers/trigger_datasets/fixed_keys_dataset.py
modyn/supervisor/internal/triggers/utils.py
modyn/tests/supervisor/internal/triggers/test_datadrifttrigger.py
modyn/tests/supervisor/internal/triggers/trigger_datasets/test_fixed_keys_dataset.py

This changes the way we build the reference and current data windows in drift detection: We implement amount- and time-based windowing that is independent of triggering.

Windowing for data drift detection

---

modyn/config/schema/pipeline/trigger/drift/alibi_detect.py

fix: Fix minor issue in alibi detect config

---

analytics/app/data/transform.py
modyn/config/schema/pipeline/trigger/drift/alibi_detect.py
modyn/supervisor/internal/pipeline_executor/models.py
modyn/tests/supervisor/internal/eval/test_eval_handler.py

fix: Adjust analytics tool for batch eval format

---

analytics/tools/patch_logfile.ipynb

This patching tool also needs some adjustments for the batched evaluation format

fix: Adjust tool for new eval format

---

benchmark/sigmod/triggering/run_yb_triggering.py
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/arxiv_datadrift.yaml
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/huffpost_datadrift.yaml
benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/yearbook_datadrift.yaml
experiments/arxiv/compare_trigger_policies/run.py
experiments/huffpost/compare_trigger_policies/run.py
experiments/yearbook/compare_trigger_policies/run.py
modyn/config/schema/pipeline/trigger/common/batched.py
modyn/config/schema/pipeline/trigger/drift/config.py
modyn/config/schema/pipeline/trigger/performance/performance.py
modyn/supervisor/internal/triggers/amounttrigger.py
modyn/supervisor/internal/triggers/batchedtrigger.py
modyn/supervisor/internal/triggers/datadrifttrigger.py
modyn/supervisor/internal/triggers/performancetrigger.py
modyn/supervisor/internal/triggers/timetrigger.py
modyn/tests/evaluator/internal/test_pytorch_evaluator.py
modyn/tests/supervisor/internal/triggers/drift/detection_window/amount.py
modyn/tests/supervisor/internal/triggers/drift/detection_window/time_.py
modyn/tests/supervisor/internal/triggers/test_datadrifttrigger.py
modyn/tests/supervisor/internal/triggers/test_performancetrigger.py

To eliminate the batching code duplication in the trigger implementations by moving it into a dedicated abstract base class.

refactor: Add `BatchedTrigger`

---

modyn/config/schema/pipeline/trigger/drift/evidently.py
modyn/supervisor/internal/pipeline_executor/evaluation_executor.py
modyn/supervisor/internal/triggers/drift/detector/evidently.py
modyn/tests/supervisor/internal/triggers/drift/test_evidently_detector.py

Support `Hellinger distance` even though it's not directly supported by `evidently` or `alibi-detect`.

feat: Add `Hellinger` distance

---

.github/workflows/workflow.yaml
environment.yml
modyn/evaluator/internal/dataset/evaluation_dataset.py
modyn/evaluator/internal/metrics/roc_auc.py
modyn/supervisor/internal/pipeline_executor/evaluation_executor.py
modyn/supervisor/internal/pipeline_executor/pipeline_executor.py
modyn/tests/evaluator/internal/metrics/test_roc_auc.py

Mostly computation of ROC on 1 sample

fix: Fix several issues 

---

analytics/plotting/common/heatmap.py

Not sure why my local pre commit hooks/even just running mypy doesn't catch this, probably some inconsistency between CI config and local config

hotfix: Fix type hint

---

modyn/evaluator/internal/metrics/accuracy.py
modyn/tests/evaluator/internal/metrics/test_accuracy.py

hotfix: Fix Accuracy metric
