eth-easl/modyn

modyn/common/benchmark/__init__.py, modyn/common/benchmark/stopwatch.py, modyn/storage/internal/file_watcher/new_file_watcher.py
This adds a stopwatch for performance benchmarks. Only to be used for Modyn development (internal tooling).
Next step would be actually creating a big json containing timing for all steps in the pipeline and output this measurement json (if requested from the user) for a pipeline.
Closes #239.
=> Add `Stopwatch` for performance benchmarks

.github/actions/base/action.yml, initial_setup.sh
When using the regular cuda image, tests fail due to no space being left on the device.
=> Use python image in CI due to space issues on Github Runners

docker/Trainer_Server/Dockerfile
As discussed in https://github.com/NVIDIA/apex/issues/1594, it appears the only solution to make apex build on a recent release is to ignore the build dependencies during packaging... Otherwise, we get the error that the `packaging` package is missing, although we explicitly install it.
=> Fix Apex Build

environment.yml, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_gradnorm_downsampling.py
It appears that `grpcio` 1.57.0 on conda breaks communication between our components. The pip version does not have that behavior. We should (temporarily) switch to install grpcio from pip.
=> Install `grpcio` via pip

environment.yml
It appears that currently any version above 1.59.0 breaks for us.
=> Pin version for `grpcio`

black.toml, setup.cfg, setup.py
Short fix for running `python_compliance.sh` script.
=> Ignore autogenerated files in compliance script

integrationtests/supervisor/integrationtest_supervisor.py, integrationtests/utils.py, modyn/models/__init__.py, modyn/models/dummy/__init__.py, modyn/models/dummy/dummy.py, modyn/tests/models/test_dummy.py
This PR adds a Dummy model that has only an Identity layer to the models.
The Dummy model is used instead of ResNet18 in integration tests to reduce CI resource consumption.
=> Add a Dummy model for integration tests

docker-compose.yml, docker/Base/Dockerfile
Per the title, I reduced files copied into the docker image.
Currently almost all files in the repository are copied into the image. This has the downside that whenever I changed a irrelevant file (a file not used to build the image environment), docker invalidates previous image caches and has to build the image from scratch, which takes 1-2 unnecessary minutes. Now this time is saved.
Also a port mistake is corrected
=> reduce files copied into image

.github/workflows/workflow.yaml, modyn/supervisor/internal/grpc/supervisor_grpc_server.py, modyn/supervisor/internal/grpc_handler.py, modyn/tests/supervisor/internal/grpc/test_supervisor_grpc_server.py, modyn/tests/supervisor/internal/test_grpc_handler.py
`num_prefetched_partitions` and `parallel_prefetch_requests` are two optional parameters in pipeline config, but required when `--evaluation-matrix` is specified. This PR makes them 1 (the default value according to the schema) when they are not specified but needed.
Additionally this PR adds a small test to increase test coverage.
=> Default prefetch configs for evaluation

benchmark/wildtime_benchmarks/benchmark_utils.py
The `create_timestamp()` function in `benchmark/wildtime_benchmarks/benchmark_utils.py` uses the **local** timezone. The generated timestamp thus is **not UTC**. 
However, modyn Storage assumes a UTC timestamp so that 1970/1/1 corresponds to 0.
Therefore, if the files are generated in Zurich local time, then 1970/1/1 is converted to -3600 in the `files` table. 
Fix tzinfo to be UTC timezone in `create_timestamp()`.
=> Fix Wildtime benchmark_utils create_timestamp() timezone to be UTC

docker-compose.yml
Actually where evaluation results are stored is `/tmp/evaluation_results`... This is a bug.
The bug causes that the pipeline log is not persistent if supervisor container exits.
=> fix volume path

.github/workflows/workflow.yaml, benchmark/mnist/mnist.yaml, benchmark/wildtime_benchmarks/example_pipelines/arxiv.yaml, benchmark/wildtime_benchmarks/example_pipelines/fmow.yaml, benchmark/wildtime_benchmarks/example_pipelines/huffpost.yaml, benchmark/wildtime_benchmarks/example_pipelines/yearbook.yaml, modyn/config/examples/modyn_config.yaml
Currently in `modyn_config.yaml` somehow there are two definitions on the arxiv dataset, (where clearly we should have only one...) I removed the wrong one as the arxiv dataset is in `csv` format.
Also, a bug on `byte_parser_function` is corrected.
=> Correct arxiv settings in modyn_config and corresponding pipeline config

environment.yml, modyn/tests/trainer_server/internal/trainer/test_pytorch_trainer.py
I suspect that it is because unfixed version of PyTorch on how to persist the `fused` option.
=> Fix unit test failure on main

benchmark/wildtime_benchmarks/data_generation_yearbook.py
Temporary fix to yearbook dataset endianness. 
Change `byteorder` to "little" in benchmark/wildtime_benchmarks/data_generate_yearbook.py.
Should check again when the C++ storage is fix.
=> Fix yearbook data generation endianness (temporary solution)

modyn/supervisor/internal/grpc_handler.py
Add missing `EvaluationStatusReporter.create_tracker()` for fixed eval datasets (`pipeline_id is None`) in supervisor grpc_handler `start_evaluation()`
=> Add create_tracker message if evaluate on fixed datasets

modyn/storage/include/internal/grpc/storage_service_impl.hpp, modyn/storage/src/internal/file_watcher/file_watcher.cpp
FileWatcher periodically monitors file status and hence is very active. Its highly frequent logs will hide the more important logs from the storage server (i.g. when processing a request.) This PR removes many noisy logs.
=> Remove noisy logs in `file_watchers.cpp`

benchmark/wildtime_benchmarks/data_generation_yearbook.py, modyn/supervisor/internal/grpc_handler.py
Fix two small bugs before adding DataDriftTrigger.
1. Temporary fix to endianness in yearbook data generation.
2. Add create_tracker() for fixed eval dataset.
=> Temporary endianess fix for yearbook and add missing tracker

integrationtests/storage/integrationtest_storage.py, modyn/evaluator/internal/dataset/evaluation_dataset.py, modyn/protos/storage.proto, modyn/storage/include/internal/grpc/storage_service_impl.hpp, modyn/storage/internal/grpc/generated/storage_pb2.py, modyn/storage/internal/grpc/generated/storage_pb2.pyi, modyn/storage/src/internal/grpc/storage_service_impl.cpp, modyn/tests/storage/internal/grpc/storage_service_impl_test.cpp
This PR makes two parameters I introduced in a previous PR https://github.com/eth-easl/modyn/pull/388 optional. Previously, I made it so that the default value "0" means no limit. I.e. a request with both `start_timestamp` and `end_timestamp` as `0` means no time restriction on the dataset.
I realized that this semantic is clumsy as sometimes we need "0" to mean the real timestamp "0". And now there is conflict. This PR makes `start_timestamp` and `end_timestamp` optional, and when they are optional, it means there is no limit. When they are set with a value, it means a limit with the numerical value.
=> Make `start_timestamp` and `end_timestamp` in evaluation gRPC requests optional

modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py
This PR makes a way to record the first and last timestamp of the data within a trigger.
This information is crucial for flexible evaluation: the first and last timestamps of the data in a trigger will be passed to the evaluation strategy introduced in https://github.com/eth-easl/modyn/pull/426, to decide what time slices of the evaluation dataset we want to evaluate against.
This PR is part of https://github.com/eth-easl/modyn/pull/422.
=> Record the time span of a trigger

modyn/config/__init__.py, modyn/config/schema/pipeline.py, modyn/supervisor/internal/supervisor.py, modyn/tests/conftest.py
This PR logs the validation error on supervisor side so that once validation fails, user knows what's going wrong and how to fix the pipeline.
Also the configuration for evaluation dataset lacks a `tokenizer`. Considering that the evaluation dataset config resembles the training dataset config, I make an inheritance.
Also the type of `transformations` are corrected.
=> Log the pydantic validation error and add tokenizer to evaluation dataset schema

modyn/trainer_server/internal/trainer/pytorch_trainer.py
In BtS downsampling, eval mode is not turned on but in StB downsampling it is turned on. This PR turns on eval mode in BtS downsampling.
=> Add missing `model.eval()` during BtS downsampling

docs/LOGGING.md, integrationtests/evaluator/integrationtest_evaluator.py, integrationtests/utils.py, modyn/config/__init__.py, modyn/config/schema/config.py, modyn/config/schema/pipeline.py, modyn/supervisor/internal/evaluation_result_writer/__init__.py, modyn/supervisor/internal/evaluation_result_writer/abstract_evaluation_result_writer.py, modyn/supervisor/internal/evaluation_result_writer/json_result_writer.py, modyn/supervisor/internal/grpc/enums.py, modyn/supervisor/internal/grpc_handler.py, modyn/supervisor/internal/pipeline_executor/PIPELINE.md, modyn/supervisor/internal/pipeline_executor/__init__.py, modyn/supervisor/internal/pipeline_executor/models.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/supervisor/internal/supervisor.py, modyn/tests/conftest.py, modyn/tests/supervisor/internal/evaluation_result_writer/test_json_result_writer.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py, modyn/tests/supervisor/internal/test_grpc_handler.py, modyn/tests/supervisor/internal/test_supervisor.py, modyn/tests/utils/test_timer.py, modyn/tests/utils/test_utils.py, modyn/trainer_server/internal/dataset/key_sources/local_key_source.py, modyn/utils/timer.py, modyn/utils/utils.py
The current state of `pipeline_executor.py` doesn't follow clear sequential or logical order. Also, the setup doesn't allow to automatically profile and log pipeline stage execution. Restructuring the orchestration of a pipeline in a PipelineExecutor here.
- Split all logical pipeline stages into separate `PipelineExecutor` member functions and merge unused PipelineStages (like `RUN_TRAINING` and `TRAINING_DONE`). This allows to have a 1:1 mapping between logical pipeline stages and member functions.
- Sort the pipeline stage functions sequentially according to their position in the pipeline
- Add `@pipeline_stage(...)` decorator which wraps every pipeline stage function. When calling the decorated function we record meta information for `logging` (post-experiment analysis) and `tracking` …
=> refactor: Adjust pipeline orchestration in `PipelineExecutor`

benchmark/mnist/mnist.yaml, benchmark/wildtime_benchmarks/example_pipelines/arxiv.yaml, benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/arxiv_datadrift.yaml, benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/huffpost_datadrift.yaml, benchmark/wildtime_benchmarks/example_pipelines/data_drift_trigger/yearbook_datadrift.yaml, benchmark/wildtime_benchmarks/example_pipelines/fmow.yaml, benchmark/wildtime_benchmarks/example_pipelines/huffpost.yaml, benchmark/wildtime_benchmarks/example_pipelines/yearbook.yaml, experiments/cloc_online_dataset/gen_pipelines.py, modyn/config/examples/example-pipeline.yaml, modyn/config/schema/pipeline.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/supervisor/internal/triggers/amounttrigger.py, modyn/supervisor/internal/triggers/datadrifttrigger.py, modyn/supervisor/internal/triggers/timetrigger.py, modyn/supervisor/internal/triggers/trigger.py, modyn/supervisor/internal/triggers/trigger_datasets/dataloader_info.py, modyn/supervisor/internal/triggers/utils.py, modyn/tests/config/test_config_integrity.py, modyn/tests/conftest.py, modyn/tests/supervisor/internal/triggers/test_amounttrigger.py, modyn/tests/supervisor/internal/triggers/test_datadrifttrigger.py, modyn/tests/supervisor/internal/triggers/test_timetrigger.py, modyn/tests/supervisor/internal/triggers/test_trigger.py, modyn/utils/utils.py, modynclient/config/examples/dummy.yaml, modynclient/config/examples/mnist.yaml
Previously it was rather hard to find out which fields and configuration items need to be set for different trigger policies, especially for drift policies as they have more parameters.
The pipeline configurations within the repository had a quite sparse coverage of the allowed flags. What is more it wasn't documented which of those fields are required, which are optional, and what the defaults are.
Now we have dedicated configuration models for every trigger policy and do not need to run the pipeline to determine if a configuration is valid. The typing alone now assures a valid configuration and makes it easier for others to configure their own triggers.
#448 will be based on this
=> refactor: Use more explicit trigger configurations

modyn/config/schema/pipeline.py
When adjusting my experimental pipeline configuration files I experienced faulty indentations. However, my pipeline only failed in the supervisor during the pipeline execution. It's desirable to fail fast (with nice error message), so let's do the validation already in the pydantic model, then we wouldn't even hand invalid function to the supervisor.
=> feat: Add function fieldvalidators 

modyn/selector/internal/selector_strategies/new_data_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_abstract_matrix_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_craig_remote_downsampling.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_gradmatch_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_gradnorm_downsample.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_kcenter_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_loss_downsample.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_submodular_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_uncertainty_downsampling_strategy.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py, modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_matrix_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_remote_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_craig_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_grad_match_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_gradnorm_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_kcenter_greedy_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_loss_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_submodular_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_uncertainty_downsampling_strategy.py
Not all downsamplers need information from autograd. With this change, we make the forward pass cheaper for those downsampling strategies.
=> feat: Enable `torch.inference_mode` if downsampler supports it

modyn/config/schema/config.py, modyn/storage/include/internal/file_wrapper/csv_file_wrapper.hpp, modyn/storage/src/internal/file_wrapper/csv_file_wrapper.cpp
Some datasets like huffpost use `rapidcsv`'s default quoting chars in their feature columns. This led to some years of the dataset not being discovered by the storage server. We want to have control over the `rapidcsv` quoting behavior within `modyn_config.yaml` to e.g. disable quoting for some datasets.
I'm not fully sure what decision lead to [skipping some samples](https://github.com/eth-easl/modyn/blob/4a9cd98bd9d199e907dc707c2e89149c5dce3f13/benchmark/wildtime_benchmarks/data_generation_arxiv.py#L20)  rather than adding those quoting options. 
As far as I can see, this addresses https://github.com/eth-easl/modyn/issues/385
- Propagate relevant `rapidcsv` parsing options to `modyn_config`.
=> fix: Fix csv quoting that broke some datasets

benchmark/cglm/README.md, benchmark/cglm/data_generation.py, benchmark/cglm/metadata_regeneration/istarmap.py, benchmark/cglm/metadata_regeneration/join_metadata.py, benchmark/cglm/metadata_regeneration/scrape.py, benchmark/cglm/metadata_regeneration/xml_to_csv.py
This adds a data generation script and some documentation on the CGLM dataset. This can be further improved but for now gets the job done. 
I also wanted to persist the scripts for scraping the metadata somewhere, but they are not cleaned at all. I am okay with this, since I do not want to put a lot of energy into that right now and we provide the final scraped data anyways, so it's mostly for documentation purposes (unless you want to scrape wikimedia for 2 weeks ;D).
=> Add description and scripts for downloading and generating the CGLM dataset

modyn/models/resnet152/resnet152.py, modyn/models/resnet18/resnet18.py, modyn/models/resnet50/resnet50.py
For CLOC/CGLM, @Sipondo suggested using a pretrained model. I somewhat agree this makes sense. Hence, I add support for loading the pretrained weights from torch. We need to call some internal functions here because we somewhat hijacked the implementation to record the embeddings. No unit tests for this because I do not want to download data in the tests, but I tested it locally and it works :)
=> feat: Support pretrained weights for ResNet models from torchvision

modyn/tests/trainer_server/internal/grpc/test_trainer_server_grpc_servicer.py, modyn/trainer_server/internal/grpc/trainer_server_grpc_servicer.py
The current availability logic in the trainer server is a bit flawed. If a training is running, the TS is considered unavailable. However, the task of figuring out resources is currently left to the client anyways: We specify the GPU and if we want to, we can start several pipelines as long as another pipeline is currently not training (but instead, e.g. evaluating). 
This lead to some experiments not working out because the trainer server not being available, although I wanted to train on a different GPU. Let's remove this old logic and keep the full responsibility at client for now. In the future, the TS should be responsible for managing its resources, but as long as the client specifies the GPU, this logic does not make sense.
=> Remove availability logic from trainer server

modyn/config/schema/pipeline/sampling/downsampling_config.py, modyn/selector/internal/selector_strategies/downsampling_strategies/rho_loss_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_rho_loss_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_rho_loss_downsampling.py
1. Make it possible to train the il model from last trigger's il model.
2. Enable `sample-then-batch` for `RHO Loss`.
Address https://github.com/eth-easl/modyn/issues/504
=> More `RHO LOSS` flavors

modyn/selector/internal/selector_strategies/coreset_strategy.py, modyn/selector/selector.py
This PR acts more as a patch rather than a fundamental fix to the asynchronism across different selector instances.
A fundamental fix should make the selection strategy *stateless*: by getting rid of the field`self._next_trigger_id` and providing it in the upstream as an argument.
This PR reduces the statefullness by removing the `self.is_warmup`.
=> Fix unsynced warmup across selector instances

modyn/config/schema/pipeline/evaluation/metric.py, modyn/supervisor/internal/eval/handler.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py
Let's increase test coverage for `EvaluationExecutor`. Testing this component is a bit nasty as it uses many other components, but okay.
=> test: Add unit tests for `evaluation_executor`

environment.yml
Numpy releases yesterday (16 June 2024) 2.0, which causes the current CI failures. This PR pins numpy to the last stable version to not block development.
=> Pin numpy to the last stable version

experiments/utils/experiment_runner.py, modynclient/client/client.py
In some benchmarking situations (e.g., yearbook), we run many many evaluations and this floods my screen and also enlighten at some point just prints bogus. Hence, I add the option (only used in benchmarking matrices) to hide the evaluation progress. 
PR 2/n of porting over changes for SIGMOD.
=> Optionally hide evaluation progress

modyn/selector/internal/selector_strategies/downsampling_strategies/uncertainty_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_uncertainty_downsampling_strategy.py
Before this, getting the downsampling params of a `UncertaintyDownsamplingStrategy` failed.
Step 3/n of porting over SIGMOD changes
=> Fix metric in `UncertaintyDownsamplingStrategy`

modyn/config/schema/pipeline/sampling/downsampling_config.py, modyn/selector/internal/selector_strategies/downsampling_strategies/uncertainty_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_rs2_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_rs2_downsampling.py
We had a couple of issues with RS2 (config not being in the union, when the training data is smaller than the expected training size). 
Part 5/n of porting over SIGMOD changes.
=> Fix various issues in RS2

environment.yml, modyn/evaluator/internal/dataset/evaluation_dataset.py, modyn/supervisor/internal/grpc_handler.py, modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/tests/trainer_server/internal/data/key_sources/test_selector_key_source.py, modyn/tests/trainer_server/internal/data/test_online_dataset.py, modyn/trainer_server/internal/dataset/key_sources/local_key_source.py, modyn/trainer_server/internal/dataset/key_sources/selector_key_source.py, modyn/trainer_server/internal/dataset/online_dataset.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py
Sometimes, we face outages/random disconnections during training. This fixes it in places where I encountered it last night. I tried to integrate `tenacity` as suggested by @robinholzi, but it's not always possible since the retry logic involves keeping track of already done work, which I don't want to put into class state
Part 6/n of porting over SIGMOD changes.
=> More robust gRPC connections, using `tenacity` where possible

modyn/trainer_server/internal/trainer/remote_downsamplers/remote_rho_loss_downsampling.py
The initial tensor resides on CPU. For me, it failed when running RHO-LOSS, since the very first `        self.rho_loss = torch.cat([self.rho_loss, training_loss - irreducible_loss]).to(training_loss.dtype)` was on two different devices, the CPU (initial tensor) and the GPU (training loss and IR loss). This PR fixes that by moving the initial tensor to the correct device.
=> Fix device for initial RHO-LOSS tensor

modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_remote_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_gradnorm_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_loss_downsampling.py
There was an unused replacement option which defaulted to True, which caused multiple keys to be chosen, which caused the storage to crash since it cannot deal with multiple keys in its current implementation. However, it should not have happened in the first place.
=> Fix replacement option in loss and gradnorm downsampling

modyn/storage/include/internal/grpc/storage_service_impl.hpp
When debugging #529 I realized this is a silent problem (we might access memory of a vector that is not allocated), so we should just explicitly fail.
=> Fail explicitly in storage when asking for duplicate keys

modyn/tests/common/grpc/test_grpc_helpers.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py
It turns out my last PR didn't rename all the variables completely, thereby causing CI failures. This PR fixes it.
=> Fix unfixed naming inconsistencies

modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py
There were some issues that evaluation results weren't collected into the logfile.
=> fix: Fix evaluation logic

modyn/config/schema/pipeline/trigger.py, modyn/supervisor/internal/eval/handler.py, modyn/supervisor/internal/triggers/timetrigger.py, modyn/supervisor/internal/utils/time_tools.py, modyn/tests/supervisor/internal/eval/test_eval_handler.py, modyn/tests/supervisor/internal/triggers/test_timetrigger.py
- We want to use the `real_last_timestamp` (start of next training interval - 1 --> marking end of current training interval) only for plotting the boxes in the heatmap plot. For decisions w.r.t. currently active models this doesn't for. E.g. if the next year in a dataset has no data at the year start, our training interval would extend into this next year and therefore it's model won't be considered for the current evaluation interval.
- timetriggers should allow starting a statically defined start point (and not with the first sample), otherwise, the whole schedule is off a couple of days.
Independently of the bug we fix with the `start_timestamp` in `timetrigger`, this setting allows us to effectively do `pre-training` with the first trigger (e.g. in the continous arxiv dataset we have …
=> fix: Adjust evaluation business logic

modyn/supervisor/internal/pipeline_executor/models.py, modyn/supervisor/internal/utils/git_utils.py
To be able to link a pipeline rune with the code that has executed it, we want to log the git sha of the last commit in the pipeline logfile.
=> feat: Log commit sha

modyn/config/schema/pipeline/config.py, modyn/config/schema/pipeline/evaluation/metrics.py, modyn/config/schema/pipeline/sampling/downsampling_config.py, modyn/selector/internal/selector_strategies/downsampling_strategies/abstract_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_rho_loss_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_scheduler.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_abstract_matrix_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_abstract_remote_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_craig_remote_downsampling.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_gradmatch_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_gradnorm_downsample.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_kcenter_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_loss_downsample.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_rho_loss_downsampling.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_rs2_downsampling.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_submodular_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_uncertainty_downsampling_strategy.py, modyn/tests/trainer_server/internal/trainer/test_pytorch_trainer.py, modyn/tests/utils/test_utils.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py, modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_matrix_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_remote_downsampling_strategy.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_craig_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_gradnorm_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_loss_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_rho_loss_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_rs2_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/remote_uncertainty_downsampling_strategy.py
Before, we only were able to enter ratios from 0-100 as percentages for downsamplers. With this PR, we allow scaling by a ratio_max factor.
=> Implement `ratio_max` scaling for downsamplers

modyn/config/schema/pipeline/sampling/config.py, modyn/selector/internal/selector_strategies/presampling_strategies/abstract_presampling_strategy.py, modyn/tests/selector/internal/selector_strategies/presampling_strategies/test_random_presampling_strategy.py
I realized we also need to set `ratio_max` for presampling strategies, otherwise they cannot run 12.5% as well.
=> Add `ratio_max` for presampling strategies

modyn/selector/internal/selector_strategies/downsampling_strategies/abstract_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_scheduler.py, modyn/tests/trainer_server/internal/trainer/test_pytorch_trainer.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py
Previously, we didn't record the number of passed batches correctly:
We use a `batch_number` which is generated purely from enumeration in `dataloader`. Therefore this number is irrelevant to the number of epochs (only shows how many batches there are in one epoch).
A similar issue exists on the iteration on `StB` when we calculate scores class by class. The number of batches passed in the previous class is not correctly accumulated on the current class.
This PR fixes it.
=> Fix batch number

analytics/tools/aggregate_runs/core_aggregation.py, analytics/tools/aggregate_runs/dir_utils.py
Sometimes a minimal number of evaluation requests are missing due to undetermined reasons. We want to allow manual inspection during aggregation with the option to ignore certain validation errors.
=> fix: Allow to ignore certain assertion errors

analytics/tools/aggregate_runs/core_aggregation.py, modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/supervisor/internal/pipeline_executor/models.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py
We want to be able to average the execution time of pipeline stage executions over multiple pipeline runs to gain more confidence in our results. For that we need sequential identifiers to map the StageLog entries from all logfiles.
=> feat: Add unique sequence number for aggregation into supervisor

environment.yml, scripts/initial_setup.sh
Otherwise, I suddenly cannot build apex (for running DLRM) anymore...
=> Add `cuda-cudart-dev` and `cuda-profiler-api` to environment

analytics/tools/aggregate_runs/core_aggregation.py, analytics/tools/aggregate_runs/pipeline_equivalence.py
- No debug mode by default
- Ignore number of evaluation workers in equivalence check
- Change logic for size check to not throw an exception
=> Fix small issues in aggregation script

analytics/app/data/transform.py, analytics/tools/aggregate_runs/core_aggregation.py, analytics/tools/aggregate_runs/pipeline_equivalence.py, analytics/tools/patch_logfile.ipynb, integrationtests/evaluator/integrationtest_evaluator.py, modyn/supervisor/internal/grpc/enums.py, modyn/supervisor/internal/pipeline_executor/PIPELINE.md, modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/supervisor/internal/pipeline_executor/models.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py
We want to utilize the batching logic introduced in https://github.com/eth-easl/modyn/pull/554 by grouping requests in the supervisor.
This will break the analytics tool because of the adjusted logging. Once we have a completed run I'll open a followup PR.
=> feat!: Batch evaluations in evaluator

modyn/config/schema/pipeline/sampling/downsampling_config.py, modyn/selector/internal/selector_strategies/coreset_strategy.py, modyn/selector/internal/selector_strategies/downsampling_strategies/abstract_downsampling_strategy.py, modyn/selector/internal/selector_strategies/downsampling_strategies/downsampling_scheduler.py, modyn/selector/internal/selector_strategies/downsampling_strategies/rho_loss_downsampling_strategy.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_rho_loss_downsampling_strategy.py, modyn/trainer_server/internal/trainer/pytorch_trainer.py, modyn/trainer_server/internal/trainer/remote_downsamplers/rho_loss_utils/irreducible_loss_producer.py
Per the title, this PR actually adds the log of downsampling phase at selector to the selector log, hence further to the pipeline log. The intention here is to see how well the il model is trained with the `record_loss_every`.
=> Add rho training log to the pipeline file

modyn/supervisor/internal/eval/handler.py, modyn/tests/supervisor/internal/eval/test_eval_handler.py
With the last training having finished before the last k evaluation intervals, those intervals will use the last model as a currently active model, however no currently trained model exists. The evaluation plots will therefore be empty at the end skewing the average of the evaluation metric.
Redefine the currently trained model to be defined on for the dataset end. The last model is allowed to be used as currently trained and currenly active model at the same time
=> fix: Adjust currently trained model to be defined for dataset end

modyn/models/rho_loss_twin_model/rho_loss_twin_model.py, modyn/selector/internal/selector_strategies/downsampling_strategies/rho_loss_downsampling_strategy.py, modyn/tests/models/test_rho_loss_twin_model.py, modyn/tests/selector/internal/selector_strategies/downsampling_strategies/test_rho_loss_downsampling_strategy.py, modyn/tests/supervisor/internal/eval/test_eval_handler.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/rho_loss_utils/test_irreducible_loss_producer.py, modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_remote_rho_loss_downsampling.py, modyn/trainer_server/internal/trainer/remote_downsamplers/rho_loss_utils/irreducible_loss_producer.py
=> Enable finetuning on `RHO-LOSS` selection strategy when `Twin` strategy is used to produce the irreducible loss model

.pre-commit-config.yaml
As we have a couple of Jupyter notebooks in the repo now, let's ensure nobody commits the notebooks without clearing the outputs.
=> feat: Add `nbstripout`

.github/actions/mamba/action.yml, .github/workflows/workflow.yaml
**Benefit**: central configuration of environment setup.
**Note**: mypy ci job will run ~1 min slower due to additional (unnecessary) dependencies in `dev-requirements.txt` and the apt install from the local action.
=> fix: Restore old caching in CI

environment.yml
CI started failing because of missing `nltk`. I suspect that some of our packages remove transitive dependency to `nltk` or introduced this new dependency without recording it in the package dependencies.
=> fix: Add `nltk` dependency

modyn/supervisor/internal/triggers/performancetrigger.py, modyn/tests/supervisor/internal/triggers/test_performancetrigger.py
We previously didn't assert the exact indexes in the tests and used returned wrong batch pointers because of the internal unprocessed samples.
=> fix: `PerformanceTrigger` batch pointer

modyn/supervisor/internal/triggers/utils/datasets/dataloader_info.py
Small quality of life improvement.  I haven't integrated the model into all the dataset implementations yet, even though most of the arguments are already in the `DataLoaderInfo`. I don't want to jump into this rabbit whole just now 😅
=> refactor: `DataLoaderInfo` dataclass

modyn/supervisor/internal/eval/handler.py, modyn/supervisor/internal/eval/strategies/abstract.py, modyn/supervisor/internal/eval/strategies/between_two_triggers.py, modyn/supervisor/internal/eval/strategies/offset.py, modyn/supervisor/internal/eval/strategies/periodic.py, modyn/supervisor/internal/eval/strategies/slicing.py, modyn/supervisor/internal/eval/strategies/static.py, modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/tests/supervisor/internal/eval/strategies/test_between_two_triggers.py, modyn/tests/supervisor/internal/eval/test_eval_handler.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py
As for the time after the last training there's no more training hence the time is not covered in an eval interval, we need to handle this case manually
=> fix: Add last interval to `BetweenTwoTriggersEvalStrategy`

modyn/config/schema/pipeline/trigger/drift/config.py, modyn/supervisor/internal/pipeline_executor/pipeline_executor.py, modyn/supervisor/internal/triggers/datadrifttrigger.py
Currently, we don't sample from drift detection windows. This parameter got lost somewhere in the midst of data drift (config) refactoring.
AmountWindowStrategies don't rely on this, but for time-based windows, we could end up with way too many samples, which makes detection very slow because of quadratic distance computation runtime.
=> fix: Add max samples for drift

modyn/supervisor/internal/triggers/batchedtrigger.py
We currently didn't log any trigger evaluation records as the batchtrigger refactoring resulted in a missing argument
=> fix: Add missing log arg

modyn/tests/trainer_server/internal/trainer/remote_downsamplers/test_get_tensor_subset.py, modyn/trainer_server/internal/trainer/remote_downsamplers/abstract_remote_downsampling_strategy.py
This is a change to replace the changes in my thesis branch to return 0-based indices in the `select_points()` method in downsamplers.
I realize that returning 0-based indices is not generalizable to all downsamplers because there are downsamplers which work class by class even in the batch-then-sample mode, e.g. craig. Therefore there is no built-in concept of 0-based indices for such downsamplers (because they pick points of the same class and select from them).
Therefore I decided to tweak the implementation of `get_tensors_subset()` which is simpler.
A time complexity of O(n) is acceptable because in any selection strategy we have to look at every sample, so an extra O(n) part can be well mixed in the time complexity of a selection strategy.
=> Speed up `get_tensors_subset` from O(n^2) to O(n)

modyn/supervisor/internal/triggers/avoidablemissclassification_costtrigger.py, modyn/supervisor/internal/triggers/performancetrigger.py, modyn/supervisor/internal/triggers/utils/models.py
For the dict, we probably do not need to change this, but let's just avoid any potential conflict.
=> fix: Do not use `model_id` in Pydantic

docs/pipeline/triggers/DRIFT_TRIGGER.md, experiments/yearbook/compare_trigger_policies/run.py, modyn/config/schema/pipeline/trigger/drift/criterion.py, modyn/config/schema/pipeline/trigger/performance/criterion.py, modyn/supervisor/internal/triggers/datadrifttrigger.py, modyn/supervisor/internal/triggers/performance/decision_policy.py, modyn/supervisor/internal/triggers/performancetrigger.py, modyn/supervisor/internal/triggers/utils/decision_policy.py, modyn/tests/supervisor/internal/triggers/drift/test_evidently_detector.py, modyn/tests/supervisor/internal/triggers/test_datadrifttrigger.py, modyn/tests/supervisor/internal/triggers/utils/test_decision_policy.py
- renamed `Percentile` > `Quantile` for more concise naming
- use np.quantile for dynamic quantile thresholds
- adapt and add more tests
=> fix!: Fix wrong directional check for low is worse metrics

.pylintrc
The pylint check `too-many-positional-arguments` limits the number of positional arguments. We do not want to limit that.
=> fix: ignore pylint `too-many-positional-argument`

.pylintrc, analytics/tools/find_invalid_runs.ipynb, modyn/evaluator/internal/grpc/evaluator_grpc_servicer.py, modyn/evaluator/internal/pytorch_evaluator.py, modyn/selector/internal/grpc/selector_grpc_servicer.py, modyn/supervisor/internal/grpc_handler.py, modyn/supervisor/internal/pipeline_executor/evaluation_executor.py, modyn/supervisor/internal/triggers/datadrifttrigger.py, modyn/tests/evaluator/internal/grpc/test_evaluator_grpc_servicer.py, modyn/tests/evaluator/internal/test_pytorch_evaluator.py, modyn/tests/supervisor/internal/pipeline_executor/test_evaluation_executor.py, modyn/tests/supervisor/internal/pipeline_executor/test_pipeline_executor.py, modyn/tests/supervisor/internal/test_grpc_handler.py
This PR addresses several issues:
1) When the evaluator crashes with an exception, we actually also send this to the supervisor
2) We validate whether we receive the correct number of results at the supervisor
3) We fix the validation of the correct number of evaluations at the evaluator
4) Some minor additions of retrying to connect in case the connection gets lost
Our observation of missing evaluations should now be caught at the first point (we actually retry on exception at the evaluator) but the others serve as a guarding mechanism.
=> feature: More resilient evaluations
